src/Entity/PanierItem.php
<?php

namespace App\Entity;

use App\Repository\PanierItemRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PanierItemRepository::class)]
class PanierItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer')]
    private $quantity;

    #[ORM\Column(type: 'string', length: 10)]
    private $size; 

    #[ORM\ManyToOne(targetEntity: Panier::class, inversedBy: 'items')]
    #[ORM\JoinColumn(nullable: false)]
    private $panier;

    #[ORM\ManyToOne(targetEntity: Product::class)]
    #[ORM\JoinColumn(nullable: false)]
    private $product;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(?Panier $panier): self
    {
        $this->panier = $panier;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;
        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->product ? $this->product->getPrice() : null;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(string $size): self
    {
        $this->size = $size;

        return $this;
    }
    
}

templates/produit/product_edit.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/product_edit.css') }}">
{% endblock %}

{% block title %}Back-office - Modifier le Produit : {{ product.name }}{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h2 class="text-center">Modifier le Produit : {{ product.name }}</h2>
        
        {{ form_start(form, {'attr': {'action': path('product_edit', { id: product.id }), 'method': 'POST'}}) }}
        
        <div class="row g-3 mt-5">
            <div class="col-md-4">
                <div>
                    {{ form_row(form.image, { 'attr': { 'onchange': 'previewImage(event)' } }) }}
                    <div id="image-preview" style="width: 200px; height: 250px; border: 1px solid #ccc; margin-top: 10px;">
                        {% if product.imageFilename %}
                            <img src="{{ asset('images-produits/' ~ product.imageFilename) }}" alt="{{ product.name }}" style="width: 100%; height: auto;">
                        {% else %}
                            <p>Aucune image disponible</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            
            <div class="col-md-8">
                {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
                {{ form_row(form.price, {'attr': {'class': 'form-control'}}) }}
                <div class="form-check mt-3">
                    {{ form_row(form.isFeatured, {'attr': {'class': 'form-check-input'}}) }}
                </div>
            </div>
        </div>

        <h3 class="mt-4 text-center">Stocks</h3>
        <div class="stocks">
            {% for stock in form.stocks %}
                <div class="stock-item mb-3 border rounded p-3">
                    <div class="row">
                        <div class="col-md-4">
                            <input type="hidden" name="{{ stock.vars.full_name }}[size]" value="{{ stock.size.vars.value }}" />
                            <div class="form-control-plaintext text-center">{{ stock.size.vars.value }}</div>
                        </div>
                        <div class="col-md-8">
                            {{ form_row(stock.quantity, { 'attr': {'class': 'form-control quantity-input', 'placeholder': 'Quantité', 'id': 'quantity-input-' ~ loop.index} }) }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
               
        <div class="d-flex flex-column justify-content-center align-items-center mt-4 mb-5">
            <button type="submit" class="btn btn-primary">Modifier</button>
            <div class="back-button mt-2 mt-4">
                <a href="{{ path('back_office') }}" class="btn btn-secondary">Retour à la page admin</a>
            </div>
        </div>
        
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/produit/product_show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/product_show.css') }}">
{% endblock %}

{% block title %}Détails du Produit{% endblock %}

{% block body %}
    <div class="container product-details">
        <div class="product-content d-flex">
            <div class="product-image">
                {% if product.imageFilename %}
                    <img src="{{ asset('images-produits/' ~ product.imageFilename) }}" alt="{{ product.name }}">
                {% else %}
                    <p>Aucune image disponible</p>
                {% endif %}
            </div>
            <div class="product-info">
                <h3>{{ product.name }}</h3>
                <p>Prix : {{ product.price }} €</p>
                
                <form action="{{ path('add_to_cart', {'id': product.id}) }}" method="POST">
                    <label for="size">Taille</label>
                    <select id="size" name="size" class="form-select mb-3">
                        <option value="XS">XS</option>
                        <option value="S">S</option>
                        <option value="M" selected>M</option>
                        <option value="L">L</option>
                        <option value="XL">XL</option>
                    </select>
                    <button type="submit" class="btn btn-primary">Ajouter au panier</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/produit/products.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/home.css') }}">
{% endblock %}

{% block title %}Tous les Produits{% endblock %}

{% block body %}
    <h2 class="text-center mt-4">Produits disponibles</h2>
    <div class="container mt-4">
        {% if Products is not empty %}
        <div class="row">
            <div class="col-md-4 mb-4 d-flex align-items-center justify-content-center">
                <div class="card border-0 body" style="background-color: #f8f9fa">
                    <form method="get" action="{{ path('shop_products') }}">
                        <div class="form-group">
                            <label for="priceRange">Filtrer par prix :</label>
                            <select name="priceRange" id="priceRange" class="form-control w-100">
                                <option value="">Tous nos produits</option>
                                <option value="10-30">10 à 30 €</option>
                                <option value="30-35">30 à 35 €</option>
                                <option value="35-50">35 à 50 €</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary mt-2 w-100">Filtrer</button>
                    </form>
                </div>
            </div>

                    
            
                {% for product in Products %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <div class="card-body">
                                <div class="text-center mb-3">
                                    <div class="product-image">
                                        {% if product.imageFilename %}
                                            <img src="{{ asset('images-produits/' ~ product.imageFilename) }}" alt="{{ product.name }}" class="img-fluid">
                                        {% else %}
                                            <p>Aucune image disponible</p>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h5 class="product-name">{{ product.name }}</h5>
                                        <p class="product-price">{{ product.price }} €</p>
                                    </div>
                                    {% if app.user %} 
                                        <a href="{{ path('product_show', { id: product.id }) }}" class="btn btn-primary">Voir</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            
            {% else %}
                <p>Aucun produit disponible.</p>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/produit/produit.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/produit.css') }}">
{% endblock %}

{% block body %}
<div class="product-container">
    <div class="product-image">
        <img src="{{ product.image }}" alt="{{ product.name }}">
    </div>
    <div class="product-details">
        <img src="{{ asset('images/' ~ product.image) }}" alt="{{ product.name }}">
        <h2>{{ product.name }}</h2>
        <p>Prix: {{ product.price }}€</p>
        <label for="size">Taille:</label>
        <select name="size" id="size">
            <option value="XS">XS</option>
            <option value="S">S</option>
            <option value="M">M</option>
            <option value="L">L</option>
            <option value="XL">XL</option>
        </select>
        <button class="add-to-cart-button">Ajouter au panier</button>
    </div>
</div>
{% endblock %}